packages:
  - "packages/aws"
allowBuilds:
  esbuild: true
  unbuild: true
  protobufjs: false
minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.10.4"
  - "@turbo/darwin-arm64@2.10.4"
  - "@turbo/linux-64@2.10.4"
  - "@turbo/linux-arm64@2.10.4"
  - "@turbo/windows-64@2.10.4"
  - "@turbo/windows-arm64@2.10.4"
  - "turbo@2.10.4"
